export const REQUEST_MATCHES = "REQUEST_MATCHES"
export const RECEIVE_MATCHES = "RECEIVE_MATCHES"
export const SHOW_RESULT = "SHOW_RESULT"
export const SHOW_ALL_RESULTS = "SHOW_ALL_RESULTS"

export const FILTER_DIRE_WINS = "FILTER_DIRE_WINS"
export const FILTER_RADIANT_WINS = "FILTER_RADIANT_WINS"
